site:
  title: Notification Hub Docs
  start_page: ROOT::index.adoc
  url: https://sophias-hub.github.io/docs

content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs

ui:
  bundle:
    url: https://github.com/antora-supplemental/valentus-theme/releases/download/v1/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui

output:
  dir: build/site

runtime:
  fetch: true
  log:
    failure_level: warn
